name: C/C++ CI

on:
  push:
    branches: [ "newvers" ]
  pull_request:
    branches: [ "newvers" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Compile C++ code
      run: g++ mainwindow.cpp
    - name: Run a program
      run: ./a.out
